(ns leiningen.shadow
  (:require [clojure.string :as string]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.java.shell :refer [sh]]
            [leiningen.core.main :as lein]
            [leiningen.run :as run]
            [meta-merge.core :refer [meta-merge]]))

(def ^:const run-shadow-cljs ["-m" "shadow.cljs.devtools.cli"])
(def ^:const shadow-cljs-preamble "
 ;;
 ;; >>>>>>>>>>>>>>>>>>>>>>>>>> DO NOT EDIT THIS FILE <<<<<<<<<<<<<<<<<<<<<<<<<<<
 ;;
 ;;
 ;;
 ;;
 ;;
 ;;
 ;; This file is generated by lein-shadow.
 ;; Any changes you make will be overwritten and lost.
 ;; Instead you should edit the value keyed :shadow-cljs in project.clj.
 ;;
 ;; More explaination: https://gitlab.com/nikperic/lein-shadow/-/tree/docs/shadow-cljs.edn.md
 ;;
 ;; Don't even check this file into your git repo. Add it to .gitignore.
 ;;
 ;;
 ;;
 ;;
 ;;
 ;;
 ;;
 ;; >>>>>>>>>>>>>>>>>>>>>>>> YOUR CHANGES WILL BE LOST <<<<<<<<<<<<<<<<<<<<<<<<<
 ;;
 ") ;; <- WARNING: A newline is required after the comment otherwise the entire
    ;;             configuration string will be commented out when concatenated.

(def windows? (string/starts-with? (System/getProperty "os.name") "Windows"))

(def npm-command
  (if windows?
    ["cmd" "/C" "npm"]
    ["npm"]))

(defn dependencies->npm-packages
  [dependencies]
  (reduce
    (fn [npm-args [package version]]
      (conj npm-args (str package "@" version)))
    []
    dependencies))

(defn dependencies->npm-args
  [dependencies dev-dependencies]
  (cond-> []
          (not-empty dependencies)
          (conj (into ["install" "--save" "--save-exact"] (dependencies->npm-packages dependencies)))

          (not-empty dev-dependencies)
          (conj (into ["install" "--save-dev" "--save-exact"] (dependencies->npm-packages dev-dependencies)))))

(defn npm-sh!
  [preamble npm-args]
  (let [command (into npm-command npm-args)]
    (lein/info "lein-shadow - running:" (string/join " " command))
    (let [result (apply sh command)]
      (case (:exit result)
        0 (lein/info "lein-shadow -" preamble (string/replace (:out result) "\n" ""))
        1 (lein/abort "lein-shadow - could not run the NPM command. NPM not found in path? Exiting.")
          (lein/abort "lein-shadow - NPM exited with an unsuccessful exit code:" (:exit result) ". Output:"
                      (:out result) (:err result))))))

(defn npm-deps!
  [dependencies dev-dependencies]
  (if (or (some? dependencies)
          (some? dev-dependencies))
    (do
      (npm-sh! "NPM version" ["--version"])
      (let [npm-args (dependencies->npm-args dependencies dev-dependencies)]
        (run! (fn [args]
                (npm-sh! "NPM install successful" args))
              npm-args)))
    (lein/info "lein-shadow - npm packages not managed, skipping npm install")))

(defn read-default-shadow-config []
  (let [file (io/file (System/getProperty "user.home") ".shadow-cljs" "config.edn")]
    (when (.exists file)
      (-> file slurp edn/read-string))))

(defn merge-config [shadow-config project-shadow-config]
  (meta-merge (dissoc shadow-config
                      :source-paths
                      :dependencies)
              project-shadow-config))

(defn merge-project [shadow-config project]
  (meta-merge (select-keys shadow-config [:source-paths :dependencies])
              project))

(defn deps-cljs
  "Reads the first `deps.cljs` file found in `:source-paths`, otherwise nil."
  [project]
  (reduce
    (fn [_ source-path]
      (when-let [file (io/file source-path "deps.cljs")]
        (when (.exists file)
          (lein/info "lein-shadow - reading NPM dependencies from" (.getPath file))
          (-> file
              (slurp)
              (edn/read-string)
              (reduced)))))
    nil
    (:source-paths project)))

(defn shadow
  "Helps keep your project configuration in your `project.clj` file when using
   shadow-cljs.

   Refer to one of the following shadow-cljs documentation sources for exhaustive
   CLI args:
   - lein run -m shadow.cljs.devtools.cli --help
   - https://shadow-cljs.github.io/docs/UsersGuide.html

   Any command that can be run as `shadow-cljs <action> <zero or more build ids>`
   can be run via Leiningen with `lein shadow <action> <zero or more build ids>`.
   Some possibilities include:

   - lein shadow compile <one or more build ids>
   - lein shadow release <one or more build ids>
   - lein shadow watch   <one or more build ids>"
  [project & args]
  (if (first args)
    (let [{:keys [npm-deps npm-dev-deps]} (or (deps-cljs project) project)]
      (npm-deps! npm-deps npm-dev-deps)
      (lein/info "lein-shadow - running shadow-cljs...")
      (if-let [config (:shadow-cljs project)]
        (let [shadow-cljs-profile (read-default-shadow-config)
              config'             (merge-config shadow-cljs-profile config)
              project'            (merge-project shadow-cljs-profile project)
              args'               (concat run-shadow-cljs args)]
          (->> (assoc config' :lein true)
               (pr-str)
               (str shadow-cljs-preamble)
               (spit "shadow-cljs.edn"))
          (apply run/run project' args'))
        (lein/warn "lein-shadow - no :shadow-cljs config key defined in project.clj. Please add a config to go into shadow-cljs.edn")))
    (lein/warn "lein-shadow - no command specified.")))
